version: '2'
services:
    landexp-app:
        image: landexp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://landexp-mysql:3306/landexp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=landexp-elasticsearch:9300
        ports:
            - 8080:8080
    landexp-mysql:
        extends:
            file: mysql.yml
            service: landexp-mysql
    landexp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: landexp-elasticsearch
